import React, { createContext, useContext, useEffect, useMemo, useRef, useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

import { useToast } from "@/hooks/use-toast";
import { apiRequest } from "@/lib/queryClient";
import { policyGenerateInputSchema, type PolicyGenerateInputValues } from "@/lib/policy-schema";

import { Wand2, FileText, Loader2 } from "lucide-react";
import { useForm } from "react-hook-form";

type NewPolicyMode = "ai" | "manual";

type NewPolicyModalContextValue = {
  setModeAndOpen: (mode: NewPolicyMode) => void;
  setModeForOpen: (mode: NewPolicyMode) => void;
  isAiGenerating: boolean;
};

const NewPolicyModalContext = createContext<NewPolicyModalContextValue | null>(null);

export function useNewPolicyModal() {
  const ctx = useContext(NewPolicyModalContext);
  if (!ctx) {
    throw new Error("useNewPolicyModal must be used within <NewPolicyModalProvider>.");
  }
  return ctx;
}

const frameworkOptions = [
  { id: "gdpr", label: "GDPR" },
  { id: "soc2", label: "SOC 2" },
  { id: "ai-act", label: "EU AI Act" },
] as const;

type FrameworkId = PolicyGenerateInputValues["frameworks"][number];

const DEFAULT_AI_VALUES: PolicyGenerateInputValues = {
  title: "Custom Policy Document",
  type: "privacy",
  description: "Generated by RegReady AI to match selected frameworks and compliance expectations.",
  frameworks: ["gdpr"],
};

export function NewPolicyModalProvider({ children }: { children: React.ReactNode }) {
  const { toast } = useToast();
  const queryClient = useQueryClient();

  const [open, setOpen] = useState(false);
  const [mode, setMode] = useState<NewPolicyMode>("ai");

  const [hasAutoStartedAi, setHasAutoStartedAi] = useState(false);

  const setModeAndOpen = (nextMode: NewPolicyMode) => {
    setMode(nextMode);
    setOpen(true);
    setHasAutoStartedAi(false);
  };

  const setModeForOpen = (nextMode: NewPolicyMode) => {
    setMode(nextMode);
    // DialogTrigger will open; we only prepare state.
    setHasAutoStartedAi(false);
  };

  const ctxValue = useMemo<NewPolicyModalContextValue>(
    () => ({
      setModeAndOpen,
      setModeForOpen,
      isAiGenerating: false, // replaced after mutation hook init below via render-time override
    }),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [],
  );

  const {
    setValue,
    watch,
    handleSubmit,
    reset,
  } = useForm<PolicyGenerateInputValues>({
    defaultValues: {
      title: "",
      type: "",
      description: "",
      frameworks: [],
    },
  });

  const title = watch("title");
  const type = watch("type");
  const description = watch("description");
  const frameworks = watch("frameworks");

  const validateWithZod = (values: PolicyGenerateInputValues) => {
    const parsed = policyGenerateInputSchema.safeParse(values);
    if (parsed.success) return parsed.data;

    const firstIssue = parsed.error.issues[0];
    toast({
      title: "Validation Error",
      description: firstIssue?.message ?? "Please check your inputs and try again.",
      variant: "destructive",
    });

    return null;
  };

  const generatePolicyMutation = useMutation({
    mutationFn: async (data: PolicyGenerateInputValues) => {
      const response = await apiRequest("POST", "/api/policies/generate", data);
      return response.json() as Promise<{
        title: string;
        content: string;
      }>;
    },
    onSuccess: async (generatedPolicy, variables) => {
      const policyData = {
        title: generatedPolicy.title,
        type: variables.type,
        description: variables.description,
        content: generatedPolicy.content,
        frameworks: variables.frameworks,
        status: "under-review",
        createdBy: "Current User",
        version: "1.0",
      };

      await apiRequest("POST", "/api/policies", policyData);

      queryClient.invalidateQueries({ queryKey: ["/api/policies"] });
      toast({
        title: "Policy Generated Successfully",
        description: "AI-powered policy draft has been created and saved.",
      });

      setOpen(false);
      setHasAutoStartedAi(false);
      reset({
        title: "",
        type: "",
        description: "",
        frameworks: [],
      });
    },
    onError: (error) => {
      const message = error instanceof Error ? error.message : "Generation failed";
      toast({
        title: "Generation Failed",
        description: message,
        variant: "destructive",
      });
    },
  });

  const createManualPolicyMutation = useMutation({
    mutationFn: async (data: PolicyGenerateInputValues) => {
      const policyData = {
        title: data.title,
        type: data.type,
        description: data.description,
        frameworks: data.frameworks,
        content: "",
        status: "draft",
        createdBy: "Current User",
        version: "1.0",
      };

      const response = await apiRequest("POST", "/api/policies", policyData);
      return response.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/policies"] });
      toast({
        title: "Policy Created",
        description: "Policy template has been created successfully.",
      });
      setOpen(false);
      setHasAutoStartedAi(false);
      reset({
        title: "",
        type: "",
        description: "",
        frameworks: [],
      });
    },
    onError: (error) => {
      const message = error instanceof Error ? error.message : "Creation failed";
      toast({
        title: "Creation Failed",
        description: message,
        variant: "destructive",
      });
    },
  });

  const isAiGenerating = generatePolicyMutation.isPending;

  const ctxValueWithIsPending = useMemo<NewPolicyModalContextValue>(
    () => ({
      setModeAndOpen,
      setModeForOpen,
      isAiGenerating,
    }),
    [isAiGenerating],
  );

  const frameworkValues = Array.isArray(frameworks) ? frameworks : [];

  const handleFrameworkChange = (frameworkId: FrameworkId, checked: boolean) => {
    const current = Array.isArray(frameworks) ? frameworks : [];
    const next = checked ? [...current, frameworkId] : current.filter((item) => item !== frameworkId);
    setValue("frameworks", next, { shouldValidate: false, shouldDirty: true });
  };

  // Auto-start AI generation when opening in AI mode.
  const autoStartRef = useRef(false);
  useEffect(() => {
    if (!open) {
      autoStartRef.current = false;
      return;
    }

    if (mode !== "ai") return;
    if (autoStartRef.current) return;

    // Prevent multiple auto-starts across re-renders.
    if (hasAutoStartedAi) return;

    autoStartRef.current = true;
    setHasAutoStartedAi(true);

    // Pre-fill defaults so the generated policy always has required fields.
    reset(DEFAULT_AI_VALUES);

    // Kick off generation immediately.
    generatePolicyMutation.mutate(DEFAULT_AI_VALUES);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, mode]);

  const submitGenerate = handleSubmit((values) => {
    const parsed = validateWithZod(values);
    if (!parsed) return;
    generatePolicyMutation.mutate(parsed);
  });

  const submitManual = handleSubmit((values) => {
    const parsed = validateWithZod(values);
    if (!parsed) return;
    createManualPolicyMutation.mutate(parsed);
  });

  const closeAndReset = () => {
    setOpen(false);
    setHasAutoStartedAi(false);
    autoStartRef.current = false;
    reset({
      title: "",
      type: "",
      description: "",
      frameworks: [],
    });
  };

  return (
    <NewPolicyModalContext.Provider value={ctxValueWithIsPending}>
      <Dialog
        open={open}
        onOpenChange={(next) => {
          if (!next) closeAndReset();
          else setOpen(next);
        }}
      >
        {children}

        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto bg-white text-black">
          <DialogHeader>
            <DialogTitle className="text-black">
              {mode === "ai" ? "Generating Policy" : "Create New Policy"}
            </DialogTitle>
            <DialogDescription className="text-black/70">
              {mode === "ai"
                ? "RegReady AI is generating a compliant policy draft now."
                : "Fill out the policy details and choose compliance frameworks."}
            </DialogDescription>
          </DialogHeader>

          <div className="pt-2">
            {mode === "ai" && isAiGenerating ? (
              <div className="flex items-center gap-3 text-neutral-800">
                <Loader2 className="h-5 w-5 animate-spin" />
                <span className="font-semibold">Generating...</span>
              </div>
            ) : null}

            <form
              className="space-y-6 text-black"
              onSubmit={(event) => event.preventDefault()}
            >
              <div>
                <Label htmlFor="type" className="text-black">
                  Policy Type
                </Label>
                <Select
                  value={type}
                  onValueChange={(value) => setValue("type", value, { shouldDirty: true })}
                  disabled={mode === "ai" && isAiGenerating}
                >
                  <SelectTrigger className="bg-white text-black border-gray-300 hover:bg-white">
                    <SelectValue placeholder="Select a policy type" />
                  </SelectTrigger>
                  <SelectContent className="bg-white text-black border-gray-300">
                    <SelectItem value="privacy" className="text-black">
                      Privacy Policy
                    </SelectItem>
                    <SelectItem value="security" className="text-black">
                      Security Policy
                    </SelectItem>
                    <SelectItem value="data-processing" className="text-black">
                      Data Processing Policy
                    </SelectItem>
                    <SelectItem value="ai-governance" className="text-black">
                      AI Governance Policy
                    </SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div>
                <Label htmlFor="title" className="text-black">
                  Policy Title
                </Label>
                <Input
                  id="title"
                  placeholder="Enter policy title"
                  value={title}
                  onChange={(event) =>
                    setValue("title", event.target.value, { shouldDirty: true })
                  }
                  disabled={mode === "ai" && isAiGenerating}
                  className="bg-white text-black border-gray-300 placeholder:text-gray-500 focus-visible:ring-black"
                />
              </div>

              <div>
                <Label className="text-black">Framework Compliance</Label>
                <div className="space-y-2 mt-2">
                  {frameworkOptions.map((framework) => (
                    <div key={framework.id} className="flex items-center space-x-2">
                      <Checkbox
                        id={framework.id}
                        checked={frameworkValues.includes(framework.id)}
                        onCheckedChange={(checked) =>
                          handleFrameworkChange(framework.id, Boolean(checked))
                        }
                        disabled={mode === "ai" && isAiGenerating}
                      />
                      <Label htmlFor={framework.id} className="text-black">
                        {framework.label}
                      </Label>
                    </div>
                  ))}
                </div>
              </div>

              <div>
                <Label htmlFor="description" className="text-black">
                  Description
                </Label>
                <Textarea
                  id="description"
                  rows={4}
                  placeholder="Describe the policy purpose and scope"
                  value={description}
                  onChange={(event) =>
                    setValue("description", event.target.value, { shouldDirty: true })
                  }
                  disabled={mode === "ai" && isAiGenerating}
                  className="bg-white text-black border-gray-300 placeholder:text-gray-500 focus-visible:ring-black"
                />
              </div>

              <div className="flex items-center space-x-4 pt-4">
                <Button
                  type="button"
                  onClick={submitGenerate}
                  disabled={isAiGenerating || mode === "ai"}
                  className="flex-1"
                >
                  {isAiGenerating ? (
                    <>
                      <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                      Generating...
                    </>
                  ) : (
                    <>
                      <Wand2 className="w-4 h-4 mr-2" />
                      Generate with AI
                    </>
                  )}
                </Button>

                <Button
                  type="button"
                  variant="outline"
                  onClick={submitManual}
                  disabled={createManualPolicyMutation.isPending}
                  className="flex-1"
                >
                  <FileText className="w-4 h-4 mr-2" />
                  {createManualPolicyMutation.isPending ? "Creating..." : "Build New Policy"}
                </Button>
              </div>

              <div className="pt-2">
                <p className="text-xs text-neutral-500">
                  Tip: “Generate with AI” is the AI generate path. “Build New Policy” creates a draft template.
                </p>
              </div>
            </form>
          </div>
        </DialogContent>
      </Dialog>
    </NewPolicyModalContext.Provider>
  );
}
