import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import type { Policy, AuditReport } from '@shared/schema';

/**
 * Returns a writable directory for generated PDFs.
 * 
 * In packaged (Electron) mode:
 *   %APPDATA%/RegReady Local Pro/generated-pdfs/
 * 
 * In development mode:
 *   <project_root>/generated-pdfs/
 * 
 * This avoids crashes when the app is packaged, because process.cwd()
 * points to the read-only "resources" directory inside the ASAR archive.
 */
function getGeneratedPdfsDir(): string {
  if (process.env.REGREADY_PDF_DIR) {
    return process.env.REGREADY_PDF_DIR;
  }

  const moduleDir = path.dirname(fileURLToPath(import.meta.url));
  const isPackagedFolder = moduleDir.includes('win-unpacked') || moduleDir.includes('app.asar');

  if (isPackagedFolder) {
    const appDataFolder = path.join(process.env.APPDATA || '', 'RegReady Local Pro');
    const pdfDir = path.join(appDataFolder, 'generated-pdfs');
    if (!fs.existsSync(pdfDir)) {
      fs.mkdirSync(pdfDir, { recursive: true });
    }
    return pdfDir;
  }

  return path.join(process.cwd(), 'generated-pdfs');
}

export async function generatePolicyPDF(policy: Policy): Promise<string> {
  const doc = new PDFDocument();
  const filename = `policy-${policy.id}-${Date.now()}.pdf`;
  const pdfDir = getGeneratedPdfsDir();
  const filepath = path.join(pdfDir, filename);

  // Directory is created by getGeneratedPdfsDir() if needed

  const stream = fs.createWriteStream(filepath);
  doc.pipe(stream);

  // Header
  doc.fontSize(20).text('RegReady Compliance Platform', { align: 'center' });
  doc.moveDown();
  
  // Policy title
  doc.fontSize(18).text(policy.title, { align: 'center' });
  doc.moveDown();

  // Metadata
  doc.fontSize(12);
  doc.text(`Policy Type: ${policy.type}`);
  doc.text(`Version: ${policy.version}`);
  doc.text(`Status: ${policy.status}`);
  doc.text(`Created: ${new Date(policy.createdAt).toLocaleDateString()}`);
  doc.text(`Last Updated: ${new Date(policy.updatedAt).toLocaleDateString()}`);
  
  if (policy.frameworks && policy.frameworks.length > 0) {
    doc.text(`Compliance Frameworks: ${policy.frameworks.join(', ')}`);
  }
  
  doc.moveDown();

  // Description
  if (policy.description) {
    doc.fontSize(14).text('Description', { underline: true });
    doc.fontSize(12).text(policy.description);
    doc.moveDown();
  }

  // Content
  if (policy.content) {
    doc.fontSize(14).text('Policy Content', { underline: true });
    doc.fontSize(12).text(policy.content);
  }

  // Footer
  doc.fontSize(10).text(
    `Generated by RegReady on ${new Date().toLocaleDateString()}`,
    50,
    doc.page.height - 50,
    { align: 'center' }
  );

  doc.end();

  return new Promise((resolve, reject) => {
    stream.on('finish', () => resolve(filepath));
    stream.on('error', reject);
  });
}

export async function generateComplianceReportPDF(params: {
  title: string;
  templateId: string;
  format: "pdf" | "docx" | "excel";
  includeCertification: boolean;
  frameworks: string[];
  // DB-derived policy evidence
  policies: Array<Pick<Policy, "id" | "title" | "type" | "version" | "status" | "createdAt" | "updatedAt" | "description" | "content" | "frameworks">>;
  // Optional: if frontend passes section selection, we only use it for layout.
  sections: string[];
}): Promise<string> {
  const doc = new PDFDocument();
  const filename = `compliance-report-${params.templateId}-${Date.now()}.pdf`;
  const pdfDir = getGeneratedPdfsDir();
  const filepath = path.join(pdfDir, filename);

  const stream = fs.createWriteStream(filepath);
  doc.pipe(stream);

  // Header
  doc.fontSize(20).text("RegReady Compliance Platform", { align: "center" });
  doc.moveDown();

  // Title
  doc.fontSize(18).text(params.title, { align: "center" });
  doc.moveDown();

  // Metadata
  doc.fontSize(12);
  doc.text(`Template: ${params.templateId}`);
  doc.text(`Format: ${params.format}`);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`);
  doc.text(`Included certification pages: ${params.includeCertification ? "Yes" : "No"}`);
  doc.moveDown();

  // Frameworks
  doc.fontSize(14).text("Framework Coverage", { underline: true });
  doc.fontSize(12);
  if (params.frameworks.length > 0) doc.text(`Frameworks: ${params.frameworks.join(", ")}`);
  else doc.text("Frameworks: (none)");
  doc.moveDown();

  // Sections (layout only)
  const sections = Array.isArray(params.sections) && params.sections.length > 0 ? params.sections : ["Executive Summary", "Compliance Status", "Recommendations"];
  doc.fontSize(14).text("Report Sections", { underline: true });
  doc.fontSize(12);
  sections.forEach((s) => doc.text(`• ${s}`));
  doc.moveDown();

  // Executive summary (DB-derived counts)
  const approvedCount = params.policies.filter((p) => p.status === "approved" || p.status === "final").length;
  const pendingCount = params.policies.filter((p) => p.status === "under-review").length;
  const draftCount = params.policies.filter((p) => p.status === "draft").length;

  doc.fontSize(14).text("Executive Summary (DB-derived)", { underline: true });
  doc.fontSize(12);
  doc.text(`Policies found: ${params.policies.length}`);
  doc.text(`Approved/Final: ${approvedCount}`);
  doc.text(`Under review: ${pendingCount}`);
  doc.text(`Draft: ${draftCount}`);
  doc.moveDown();

  // Compliance status (policy evidence list)
  doc.fontSize(14).text("Compliance Evidence (Policies)", { underline: true });
  doc.fontSize(12);

  if (params.policies.length === 0) {
    doc.text("No policy evidence found in the database for the selected workspace/frameworks.");
  } else {
    params.policies.slice(0, 30).forEach((p, idx) => {
      doc.fontSize(12).text(`${idx + 1}. ${p.title}`);
      doc.fontSize(10).text(`Type: ${p.type} • Version: ${p.version} • Status: ${p.status}`);
      if (p.description) doc.fontSize(10).text(`Description: ${p.description}`);
      if (p.frameworks?.length) doc.fontSize(10).text(`Frameworks: ${p.frameworks.join(", ")}`);
      doc.moveDown(0.3);
    });
  }
  doc.moveDown();

  // Certification pages (layout-only; placeholder)
  if (params.includeCertification) {
    doc.fontSize(14).text("Compliance Certification Pages", { underline: true });
    doc.fontSize(12);
    doc.text("Certification details would be rendered here using signed attestations & evidence bundles.");
    doc.text("For now, this section is generated based on DB evidence counts.");
    doc.moveDown();
  }

  // Footer
  doc.fontSize(10).text(
    `Generated by RegReady on ${new Date().toLocaleDateString()}`,
    50,
    doc.page.height - 50,
    { align: "center" }
  );

  doc.end();

  return new Promise((resolve, reject) => {
    stream.on("finish", () => resolve(filepath));
    stream.on("error", reject);
  });
}

export async function generateRiskAssessmentPDF(params: {
  description: string;
  frameworks: string[];
  riskLevel: string;
  riskScore: number;
  recommendations: string[];
  frameworkSpecificRisks: Record<string, string>;
}): Promise<string> {
  const doc = new PDFDocument();
  const filename = `risk-assessment-${Date.now()}.pdf`;
  const pdfDir = getGeneratedPdfsDir();
  const filepath = path.join(pdfDir, filename);

  const stream = fs.createWriteStream(filepath);
  doc.pipe(stream);

  // Header
  doc.fontSize(20).text("RegReady Compliance Platform", { align: "center" });
  doc.moveDown();

  // Title
  doc.fontSize(18).text("Risk Assessment Report", { align: "center" });
  doc.moveDown();

  // Metadata
  doc.fontSize(12);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`);
  doc.text(`Risk Level: ${params.riskLevel}`);
  doc.text(`Risk Score: ${params.riskScore}/100`);

  if (params.frameworks?.length) {
    doc.text(`Frameworks: ${params.frameworks.join(", ")}`);
  }
  doc.moveDown();

  // Scenario
  doc.fontSize(14).text("Scenario", { underline: true });
  doc.fontSize(12).text(params.description || "(none provided)");
  doc.moveDown();

  // Recommendations
  doc.fontSize(14).text("Recommendations", { underline: true });
  doc.fontSize(12);

  if (Array.isArray(params.recommendations) && params.recommendations.length > 0) {
    params.recommendations.forEach((rec, idx) => {
      doc.text(`${idx + 1}. ${rec}`);
    });
  } else {
    doc.text("No recommendations returned.");
  }
  doc.moveDown();

  // Framework-specific risks
  doc.fontSize(14).text("Framework-specific risks", { underline: true });
  doc.fontSize(12);

  const entries = Object.entries(params.frameworkSpecificRisks || {});
  if (entries.length > 0) {
    entries.forEach(([key, value]) => {
      doc.fontSize(12).text(`${key.toString().toUpperCase()}:`);
      doc.fontSize(12).text(value || "");
      doc.moveDown(0.5);
    });
  } else {
    doc.text("No framework-specific risks returned.");
  }

  // Footer
  doc.fontSize(10).text(
    `Generated by RegReady on ${new Date().toLocaleDateString()}`,
    50,
    doc.page.height - 50,
    { align: "center" }
  );

  doc.end();

  return new Promise((resolve, reject) => {
    stream.on("finish", () => resolve(filepath));
    stream.on("error", reject);
  });
}

export async function generateAuditReportPDF(report: AuditReport): Promise<string> {
  const doc = new PDFDocument();
  const filename = `audit-report-${report.id}-${Date.now()}.pdf`;
  const pdfDir = getGeneratedPdfsDir();
  const filepath = path.join(pdfDir, filename);

  const stream = fs.createWriteStream(filepath);
  doc.pipe(stream);

  // Header
  doc.fontSize(20).text('RegReady Compliance Audit Report', { align: 'center' });
  doc.moveDown();
  
  // Report title
  doc.fontSize(18).text(report.title, { align: 'center' });
  doc.moveDown();

  // Metadata
  doc.fontSize(12);
  doc.text(`Report Type: ${report.type}`);
  if (report.framework) {
    doc.text(`Framework: ${report.framework}`);
  }
  doc.text(`Status: ${report.status}`);
  doc.text(`Generated: ${new Date(report.generatedAt).toLocaleDateString()}`);
  doc.text(`Generated By: ${report.generatedBy}`);
  doc.moveDown();

  // Executive Summary
  if (report.summary) {
    doc.fontSize(14).text('Executive Summary', { underline: true });
    doc.fontSize(12).text(report.summary);
    doc.moveDown();
  }

  // Findings
  if (report.findings && report.findings.length > 0) {
    doc.fontSize(14).text('Key Findings', { underline: true });
    doc.fontSize(12);
    report.findings.forEach((finding, index) => {
      doc.text(`${index + 1}. ${typeof finding === 'string' ? finding : JSON.stringify(finding)}`);
    });
    doc.moveDown();
  }

  // Recommendations
  if (report.recommendations && report.recommendations.length > 0) {
    doc.fontSize(14).text('Recommendations', { underline: true });
    doc.fontSize(12);
    report.recommendations.forEach((rec, index) => {
      doc.text(`${index + 1}. ${rec}`);
    });
    doc.moveDown();
  }

  // Footer
  doc.fontSize(10).text(
    `Generated by RegReady on ${new Date().toLocaleDateString()}`,
    50,
    doc.page.height - 50,
    { align: 'center' }
  );

  doc.end();

  return new Promise((resolve, reject) => {
    stream.on('finish', () => resolve(filepath));
    stream.on('error', reject);
  });
}
